name: ci

on:
- pull_request
- push

permissions:
  contents: read

jobs:
  test:
    name: Node.js ${{ matrix.node-version }} - Express ${{ matrix.express-version }}
    permissions:
      checks: write  # for coverallsapp/github-action to create new checks
      contents: read  # for actions/checkout to fetch code
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
        - "18"
        - "19"
        - "20"
        - "21"
        - "22"
        - "23"
        - "24"
        - "25"
        express-version:
        - "4"
        - "5"

    steps:
    - uses: actions/checkout@v4

    - name: Install Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Node.js dependencies
      run: npm install

    - name: Install Express ${{ matrix.express-version }}
      run: npm install express@${{ matrix.express-version }}

    - name: List environment
      shell: bash
      run: |
        echo "node@$(node -v)"
        echo "npm@$(npm -v)"
        npm list express
        npm -s ls ||:

    - name: Run tests
      run: ${{ matrix.node-version == '18' && 'npm test' || 'npm run test-ci' }}

    - name: Lint code
      run: npm run lint

    - name: Collect code coverage
      if: matrix.node-version != '18'
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        flag-name: run-node${{ matrix.node-version }}-express${{ matrix.express-version }}
        parallel: true

  coverage:
    permissions:
      checks: write  # for coverallsapp/github-action to create new checks
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Upload code coverage
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true
